

server:
  port: 8082

spring:
  cloud:
    stream:
      binders:
        kafka-loan:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
      bindings:
        listen-in-0:
          destination: t1_demo_client_transaction_errors
          group: t1_bank
          content-type: application/json

  application:
    name: CorrectionService

retry:
  interval:
    ms: 60000

service:
  client-service: http://localhost:8080/api