server:
  port: 8082

spring:
  cloud:
    stream:
      binders:
        kafka-loan:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
      bindings:
        listen-in-0:
          destination: t1_demo_client_transaction_errors
          group: t1_bank
          content-type: application/json

  application:
    name: CorrectionService

  datasource:
    url: jdbc:postgresql://localhost:5433/t1_bank_demo
    username: postgres
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/master-changelog.yaml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/t1_bank_demo
    user: postgres
    password: "0000"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

retry:
  interval:
    ms: 60000